name: My Manifest File
description: My First Manifest File 💚
aggregation:
  metrics:
    - 'carbon'
  type: 'both'
initialize:
  outputs: ['yaml', 'csv']
  plugins: 
    group-by: 
      path: 'builtin'
      method: GroupBy   
    operational-carbon:
      path: '@grnsft/if-plugins'
      method: Multiply
      global-config:
        input-parameters: ['cpu/energy', 'grid/carbon-intensity']
        output-parameter: 'carbon'       
    watttime:
      path: '@grnsft/if-unofficial-plugins'           
      method: WattTimeGridEmissions    
    teads-curve:
      path: '@grnsft/if-unofficial-plugins'
      method: TeadsCurve
      global-config:
        interpolation: spline  
    cloud-metadata:
      method: CloudMetadata
      path: "@grnsft/if-plugins"   
    fake-importer:
      path: '@grnsft/if-plugins'
      method: MockObservations
      global-config:
        timestamp-from: '2024-03-05T00:00:00.000Z'
        timestamp-to: '2024-03-05T01:00:00.000Z'
        duration: 300
        components:
          - name: server-1
            cloud/instance-type: Standard_E64_v3
            application: db
            team: data
          - name: server-2
            cloud/instance-type: Standard_E64_v3
            application: db
            team: data
          - name: server-3
            cloud/instance-type: Standard_E64_v3
            application: cache
            team: data
          - name: server-4
            cloud/instance-type: Standard_E64_v3
            application: api
            team: dev
          - name: server-5
            cloud/instance-type: Standard_E64_v3
            application: api
            team: dev
        generators:
          common:
            cloud/vendor: azure
            cloud/region: westus3
          randint:
            cpu/utilization:
              min: 1
              max: 99           
    time-sync:
      method: TimeSync
      path: "builtin"
      global-config: 
        start-time: '2024-03-05T00:00:00.000Z'
        end-time: '2024-03-05T01:00:00.000Z'
        interval: 900
        allow-padding: true
tree: 
  pipeline:
    - fake-importer
    - group-by
    - time-sync
    - cloud-metadata
    - teads-curve
    # - watttime
    - operational-carbon
  defaults:
    grid/carbon-intensity: 500
  config:
    group-by:
      group:
        - cloud/vendor
        - cloud/region
        - application
        - name
  inputs: null