name: My Manifest File
description: My First Manifest File 💚
initialize:
  outputs: ['yaml']
  plugins: 
    copy-param:
      path: 'copy-plugin'
      method: Copy      
      global-config:
        keep-existing: true    
    operational-carbon:
      path: '@grnsft/if-plugins'
      method: Multiply
      global-config:
        input-parameters: ['cpu/energy', 'grid/carbon-intensity']
        output-parameter: 'carbon'      
    watttime:
      path: '@grnsft/if-unofficial-plugins'           
      method: WattTimeGridEmissions      
    teads-curve:
      path: '@grnsft/if-unofficial-plugins'
      method: TeadsCurve
      global-config:
        interpolation: spline    
    cloud-metadata:
      method: CloudMetadata
      path: "@grnsft/if-plugins"        
    import-data:
      path: '@grnsft/if-plugins'
      method: MockObservations
      global-config:
        timestamp-from: 2024-03-05T00:00
        timestamp-to: 2024-03-05T01:00
        duration: 300
        components:
          - name: server-1
            cloud/instance-type: Standard_E64_v3
          - name: server-2
            cloud/instance-type: Standard_E64_v3            
        generators:
          common:
            cloud/vendor: azure
            cloud/region: westus3
            grid/carbon-intensity: 500
          randint:
            cpu/utilization:
              min: 1
              max: 99               
tree: 
  pipeline:
    - import-data
    - cloud-metadata
    - teads-curve
    - operational-carbon
    - copy-param
  # defaults:
  #   grid/carbon-intensity: 500
  config: 
    copy-param: 
      from-param: cpu/energy
      to-param: energy
