name: My Manifest File
description: My First Manifest File 💚
aggregation:
  metrics:
    - 'carbon'
    - 'cpu/energy'
  type: 'both'
initialize:
  outputs: ['yaml', 'csv']
  params: 
  - name: wue  # todo move this into if params.ts file
    description: Water Usage Effectiveness 
    aggregation: sum
    unit: L/kWh
  plugins: 
    group-by: 
      path: 'builtin'
      method: GroupBy
    #sampler:
      #method: Shell
      #path: '@grnsft/if-plugins'
      #global-config:
        #command: python3 ./sampler.py
    #copy-param:
      #path: 'copy-plugin'
      #method: Copy      
      #global-config:
        #keep-existing: true       
    operational-carbon:
      path: '@grnsft/if-plugins'
      method: Multiply
      global-config:
        input-parameters: ['cpu/energy', 'grid/carbon-intensity']  # kWh x gCO2eq/kWh
        output-parameter: 'carbon'  # gCO2eq
    operational-water:
      path: '@grnsft/if-plugins'
      method: Multiply
      global-config:
        input-parameters: ['cpu/energy', 'wue'] # kWh x L/kWh
        output-parameter: 'water'  # L      
    watttime:
      path: '@grnsft/if-unofficial-plugins'           
      method: WattTimeGridEmissions    
    teads-curve:
      path: '@grnsft/if-unofficial-plugins'
      method: TeadsCurve
      global-config:
        interpolation: spline  
    cloud-metadata:
      method: CloudMetadata
      path: "@grnsft/if-plugins"   
    mock-observations:
      path: '@grnsft/if-plugins'
      method: MockObservations
      global-config:
        timestamp-from: '2024-03-05T00:00:00.000Z'
        timestamp-to: '2024-03-05T01:00:00.000Z'
        duration: 300
        components:
          - name: server-westus3-1  # Azure westus3
            cloud/vendor: azure
            cloud/instance-type: Standard_E64_v3
            cloud/region: westus3
            application: db
            team: data
          - name: server-westus3-2
            cloud/vendor: azure
            cloud/instance-type: Standard_E64_v3
            cloud/region: westus3
            application: db
            team: data
          - name: server-westus3-3
            cloud/vendor: azure
            cloud/instance-type: Standard_E64_v3
            cloud/region: westus3
            application: cache
            team: data
          - name: server-westus3-4
            cloud/vendor: azure
            cloud/instance-type: Standard_E64_v3
            cloud/region: westus3
            application: api
            team: dev
          - name: server-westus3-5
            cloud/vendor: azure
            cloud/instance-type: Standard_E64_v3
            cloud/region: westus3
            application: api
            team: dev
          - name: server-westus2-1  # Azure westus2
            cloud/vendor: azure
            cloud/instance-type: Standard_E64_v3
            cloud/region: westus2
            application: db
            team: data
          - name: server-westus2-2
            cloud/vendor: azure
            cloud/instance-type: Standard_E64_v3
            cloud/region: westus2
            application: db
            team: data
          - name: server-westus2-3
            cloud/vendor: azure
            cloud/instance-type: Standard_E64_v3
            cloud/region: westus2
            application: cache
            team: data
          - name: server-westus2-4
            cloud/vendor: azure
            cloud/instance-type: Standard_E64_v3
            cloud/region: westus2
            application: api
            team: dev
          - name: server-westus2-5
            cloud/vendor: azure
            cloud/instance-type: Standard_E64_v3
            cloud/region: westus2
            application: api
            team: dev                  
          - name: server-us-west-1-1  # AWS us-west-1
            cloud/vendor: aws
            cloud/instance-type: r4.16xlarge
            cloud/region: us-west-1
            application: db
            team: data
          - name: server-us-west-1-2
            cloud/vendor: aws
            cloud/instance-type: r4.16xlarge
            cloud/region: us-west-1
            application: db
            team: data
          - name: server-us-west-1-3
            cloud/vendor: aws
            cloud/instance-type: r4.16xlarge
            cloud/region: us-west-1
            application: cache
            team: data
          - name: server-us-west-1-4
            cloud/vendor: aws
            cloud/instance-type: r4.16xlarge
            cloud/region: us-west-1
            application: api
            team: dev
          - name: server-us-west-1-5
            cloud/vendor: aws
            cloud/instance-type: r4.16xlarge
            cloud/region: us-west-1
            application: api
            team: dev
          - name: server-us-west-1-1  # GCP us-west-1
            cloud/vendor: aws
            cloud/instance-type: r4.16xlarge
            cloud/region: us-west-1
            application: db
            team: data
          - name: server-us-west-1-2
            cloud/vendor: aws
            cloud/instance-type: r4.16xlarge
            cloud/region: us-west-1
            application: db
            team: data
          - name: server-us-west-1-3
            cloud/vendor: aws
            cloud/instance-type: r4.16xlarge
            cloud/region: us-west-1
            application: cache
            team: data
          - name: server-us-west-1-4
            cloud/vendor: aws
            cloud/instance-type: r4.16xlarge
            cloud/region: us-west-1
            application: api
            team: dev
          - name: server-us-west-1-5
            cloud/vendor: aws
            cloud/instance-type: r4.16xlarge
            cloud/region: us-west-1
            application: api
            team: dev                    
        generators:
          common:
            #cloud/vendor: azure
            common-key: common-val  # Dummy data just to get this to run
          randint:
            cpu/utilization:
              min: 1
              max: 99           
    time-sync:
      method: TimeSync
      path: "builtin"
      global-config: 
        start-time: '2024-03-05T00:00:00.000Z'
        end-time: '2024-03-05T01:00:00.000Z'
        interval: 300
        allow-padding: true
tree: 
  pipeline:
    - mock-observations
    - group-by
    - time-sync
    - cloud-metadata
    - watttime   # calculates grid/carbon-intensity
    - teads-curve  # calculates cpu/energy
    - operational-carbon
    - operational-water
    #- sampler
  defaults:
    #grid/carbon-intensity: 500
  config:
    group-by:
      group:
        - cloud/vendor
        - cloud/region
        - application
        - name
    #copy-param: 
      #from-param: cpu/energy
      #to-param: energy
  inputs: null
